Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/usr/local/lib/python3.11/dist-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/usr/local/lib/python3.11/dist-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/local/lib/python3.11/dist-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Tentukan jumlah tetangga untuk LOF
n_neighbors = 20

# Deteksi outlier menggunakan Local Outlier Factor (LOF)
lof = LocalOutlierFactor(n_neighbors=n_neighbors, contamination=0.1)
y_pred = lof.fit_predict(data_values)
df_merged["outlier_lof"] = y_pred == -1
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-5-fcc169bb0fc8>[0m in [0;36m<cell line: 0>[0;34m()[0m
[1;32m      3[0m [0;34m[0m[0m
[1;32m      4[0m [0;31m# Deteksi outlier menggunakan Local Outlier Factor (LOF)[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 5[0;31m [0mlof[0m [0;34m=[0m [0mLocalOutlierFactor[0m[0;34m([0m[0mn_neighbors[0m[0;34m=[0m[0mn_neighbors[0m[0;34m,[0m [0mcontamination[0m[0;34m=[0m[0;36m0.1[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      6[0m [0my_pred[0m [0;34m=[0m [0mlof[0m[0;34m.[0m[0mfit_predict[0m[0;34m([0m[0mdata_values[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      7[0m [0mdf_merged[0m[0;34m[[0m[0;34m"outlier_lof"[0m[0;34m][0m [0;34m=[0m [0my_pred[0m [0;34m==[0m [0;34m-[0m[0;36m1[0m[0;34m[0m[0;34m[0m[0m

[0;31mNameError[0m: name 'LocalOutlierFactor' is not defined

